let order;
let CusSubDetails = steps.CusSubDetails;
if(CusSubDetails!==undefined && CusSubDetails!==null)
{
  if(CusSubDetails.order_after!==undefined && CusSubDetails.order_after!== null)
  {
    order = CusSubDetails.order_after;
  }
}
done(order);

/*let o = {
    "order_id": "1419",
    "document_number": "1027",
    "invoice_id": "Qbusite1185",
    "subscription_id": "HmjGQpxRn3rawBJvc",
    "customer_id": "HmjGQpxRn3rawBJvc",
    "status": "queued",
    "payment_status": "paid",
    "order_type": "system_generated",
    "price_type": "tax_exclusive",
    "order_date": 1578554092,
    "shipping_date": 1578554092,
    "created_by": "Auto generated by system",
    "tax": 0,
    "amount_paid": 0,
    "amount_adjusted": 12999,
    "refundable_credits_issued": 0,
    "refundable_credits": 0,
    "rounding_adjustement": 1,
    "paid_on": 1578554092,
    "exchange_rate": 1.0,
    "created_at": 1578554093,
    "updated_at": 1578554093,
    "resource_version": 1578554093602,
    "deleted": false,
    "object": "order",
    "discount": 0,
    "sub_total": 13000,
"fulfillment_status":true,
    "order_line_items": [{
        "id": "o_liHmjGQpxRn3s6agJwz",
        "invoice_id": "Qbusite1185",
        "invoice_line_item_id": "li_HmjGQpxRn3rayAJve",
        "unit_price": 13000,
        "amount": 13000,
        "fulfillment_quantity": 1,
        "fulfillment_amount": 13000,
        "tax_amount": 0,
        "amount_paid": 0,
        "amount_adjusted": 12999,
        "refundable_credits_issued": 0,
        "refundable_credits": 0,
        "is_shippable": true,
        "status": "queued",
        "object": "order_line_item",
        "entity_id": "shippable",
        "discount_amount": 0,
        "item_level_discount_amount": 0,
        "description": "shippable",
        "entity_type": "plan"
    }],
    "total": 13001,
    "currency_code": "USD",
    "base_currency_code": "USD",
    "is_gifted": false,
"gift_id" : 1234,
"cancellation_reason":"cancellation reason",
"reference_id":1234,
"tracking_id":5678,
"batch_id":9012,
"shipment_carrier":"Bus",
"invoice_round_off_amount":9800,
"status_update_at":1578554093,
"delivered_at":1578554093,
"shipped_at":1578554093,
"cancelled_at":1578554093,
"shipping_cut_off_date":1578554093,
    "billing_address": {
        "first_name": "billy",
        "validation_status": "not_validated",
        "object": "billing_address"
    },
    "linked_credit_notes": [{
        "object": "order_line_item_linked_credit",
        "id": "qbusitecn41",
        "type": "adjustment",
        "status": "adjusted",
        "amount": 12999
    }]
};

done(o);

*/